/*

 BACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : BackgroundTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 38
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackgroundMapWidth 32
#define BackgroundMapHeight 18
#define BackgroundMapBank 0

extern unsigned char BackgroundMap[];

/* End of BACKGROUNDMAP.H */
