/*

 LEVEL01MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : Level01Tuiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Level01MapWidth 32
#define Level01MapHeight 18
#define Level01MapBank 0

extern unsigned char Level01Map[];

/* End of LEVEL01MAP.H */
