/*

 WM_MSGBOX.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 4
   Tile set      : AlphabetTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define WM_msgboxWidth 20
#define WM_msgboxHeight 4
#define WM_msgboxBank 0

extern unsigned char WM_msgbox[];

/* End of WM_MSGBOX.H */
