/*

 MAZEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Dylan\Documents\GameBoy\Renouveau\tuto_gameboy\VSCprojet_tutoGB_GamingMonsters\10 sprite collision detection\MazeTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MazeMapWidth 20
#define MazeMapHeight 18
#define MazeMapBank 0

extern unsigned char MazeMap[];

/* End of MAZEMAP.H */
