/*

 WM_COMMANDSCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : AlphabetTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define WM_commandscreenWidth 20
#define WM_commandscreenHeight 18
#define WM_commandscreenBank 0

extern unsigned char WM_commandscreen[];

/* End of WM_COMMANDSCREEN.H */
