/*

 KEYBOARDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Dylan\Documents\GameBoy\Renouveau\tuto_gameboy\VSCprojet_tutoGB_GamingMonsters\14 keyboard\keyboardTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define keyboardMapWidth 20
#define keyboardMapHeight 18
#define keyboardMapBank 0

extern unsigned char keyboardMap[];

/* End of KEYBOARDMAP.H */
