/*

 BASICBACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : C:\Users\Dylan\Documents\GameBoy\Renouveau\tuto_gameboy\VSCprojet_tutoGB_GamingMonsters\04 backgrounds\BasicBackground.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackgroundMapWidth 32
#define BackgroundMapHeight 18
#define BackgroundMapBank 0

extern unsigned char BackgroundMap[];

/* End of BASICBACKGROUNDMAP.H */
