/*

 SAVESCREENMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Dylan\Documents\GameBoy\Renouveau\tuto_gameboy\VSCprojet_tutoGB_GamingMonsters\15 Bilan perso v4\keyboardTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define SavescreenMapWidth 20
#define SavescreenMapHeight 18
#define SavescreenMapBank 0

extern unsigned char SavescreenMap[];

/* End of SAVESCREENMAP.H */
