/*

 WM_RANDMESSAGES.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 4
   Tile set      : AlphabetTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define WM_randMessagesWidth 20
#define WM_randMessagesHeight 4
#define WM_randMessagesBank 0

extern unsigned char WM_randMessages[];

/* End of WM_RANDMESSAGES.H */
