/*

 LEVEL01MAPCOMPLET.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 150 x 18
   Tile set      : Level01Tuiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : Yes
   Block size    : 18

 This file was generated by GBMB v1.8

*/

#define Level01MapCompletWidth 150
#define Level01MapCompletHeight 18
#define Level01MapCompletBank 0

extern unsigned char Level01MapCompletBLK0[];
extern unsigned char Level01MapCompletBLK1[];
extern unsigned char Level01MapCompletBLK2[];
extern unsigned char Level01MapCompletBLK3[];
extern unsigned char Level01MapCompletBLK4[];
extern unsigned char Level01MapCompletBLK5[];
extern unsigned char Level01MapCompletBLK6[];
extern unsigned char Level01MapCompletBLK7[];
extern unsigned char Level01MapCompletBLK8[];
extern unsigned char Level01MapCompletBLK9[];
extern unsigned char Level01MapCompletBLK10[];
extern unsigned char Level01MapCompletBLK11[];
extern unsigned char Level01MapCompletBLK12[];
extern unsigned char Level01MapCompletBLK13[];
extern unsigned char Level01MapCompletBLK14[];
extern unsigned char Level01MapCompletBLK15[];
extern unsigned char Level01MapCompletBLK16[];
extern unsigned char Level01MapCompletBLK17[];
extern unsigned char Level01MapCompletBLK18[];
extern unsigned char Level01MapCompletBLK19[];
extern unsigned char Level01MapCompletBLK20[];
extern unsigned char Level01MapCompletBLK21[];
extern unsigned char Level01MapCompletBLK22[];
extern unsigned char Level01MapCompletBLK23[];
extern unsigned char Level01MapCompletBLK24[];
extern unsigned char Level01MapCompletBLK25[];
extern unsigned char Level01MapCompletBLK26[];
extern unsigned char Level01MapCompletBLK27[];
extern unsigned char Level01MapCompletBLK28[];
extern unsigned char Level01MapCompletBLK29[];
extern unsigned char Level01MapCompletBLK30[];
extern unsigned char Level01MapCompletBLK31[];
extern unsigned char Level01MapCompletBLK32[];
extern unsigned char Level01MapCompletBLK33[];
extern unsigned char Level01MapCompletBLK34[];
extern unsigned char Level01MapCompletBLK35[];
extern unsigned char Level01MapCompletBLK36[];
extern unsigned char Level01MapCompletBLK37[];
extern unsigned char Level01MapCompletBLK38[];
extern unsigned char Level01MapCompletBLK39[];
extern unsigned char Level01MapCompletBLK40[];
extern unsigned char Level01MapCompletBLK41[];
extern unsigned char Level01MapCompletBLK42[];
extern unsigned char Level01MapCompletBLK43[];
extern unsigned char Level01MapCompletBLK44[];
extern unsigned char Level01MapCompletBLK45[];
extern unsigned char Level01MapCompletBLK46[];
extern unsigned char Level01MapCompletBLK47[];
extern unsigned char Level01MapCompletBLK48[];
extern unsigned char Level01MapCompletBLK49[];
extern unsigned char Level01MapCompletBLK50[];
extern unsigned char Level01MapCompletBLK51[];
extern unsigned char Level01MapCompletBLK52[];
extern unsigned char Level01MapCompletBLK53[];
extern unsigned char Level01MapCompletBLK54[];
extern unsigned char Level01MapCompletBLK55[];
extern unsigned char Level01MapCompletBLK56[];
extern unsigned char Level01MapCompletBLK57[];
extern unsigned char Level01MapCompletBLK58[];
extern unsigned char Level01MapCompletBLK59[];
extern unsigned char Level01MapCompletBLK60[];
extern unsigned char Level01MapCompletBLK61[];
extern unsigned char Level01MapCompletBLK62[];
extern unsigned char Level01MapCompletBLK63[];
extern unsigned char Level01MapCompletBLK64[];
extern unsigned char Level01MapCompletBLK65[];
extern unsigned char Level01MapCompletBLK66[];
extern unsigned char Level01MapCompletBLK67[];
extern unsigned char Level01MapCompletBLK68[];
extern unsigned char Level01MapCompletBLK69[];
extern unsigned char Level01MapCompletBLK70[];
extern unsigned char Level01MapCompletBLK71[];
extern unsigned char Level01MapCompletBLK72[];
extern unsigned char Level01MapCompletBLK73[];
extern unsigned char Level01MapCompletBLK74[];
extern unsigned char Level01MapCompletBLK75[];
extern unsigned char Level01MapCompletBLK76[];
extern unsigned char Level01MapCompletBLK77[];
extern unsigned char Level01MapCompletBLK78[];
extern unsigned char Level01MapCompletBLK79[];
extern unsigned char Level01MapCompletBLK80[];
extern unsigned char Level01MapCompletBLK81[];
extern unsigned char Level01MapCompletBLK82[];
extern unsigned char Level01MapCompletBLK83[];
extern unsigned char Level01MapCompletBLK84[];
extern unsigned char Level01MapCompletBLK85[];
extern unsigned char Level01MapCompletBLK86[];
extern unsigned char Level01MapCompletBLK87[];
extern unsigned char Level01MapCompletBLK88[];
extern unsigned char Level01MapCompletBLK89[];
extern unsigned char Level01MapCompletBLK90[];
extern unsigned char Level01MapCompletBLK91[];
extern unsigned char Level01MapCompletBLK92[];
extern unsigned char Level01MapCompletBLK93[];
extern unsigned char Level01MapCompletBLK94[];
extern unsigned char Level01MapCompletBLK95[];
extern unsigned char Level01MapCompletBLK96[];
extern unsigned char Level01MapCompletBLK97[];
extern unsigned char Level01MapCompletBLK98[];
extern unsigned char Level01MapCompletBLK99[];
extern unsigned char Level01MapCompletBLK100[];
extern unsigned char Level01MapCompletBLK101[];
extern unsigned char Level01MapCompletBLK102[];
extern unsigned char Level01MapCompletBLK103[];
extern unsigned char Level01MapCompletBLK104[];
extern unsigned char Level01MapCompletBLK105[];
extern unsigned char Level01MapCompletBLK106[];
extern unsigned char Level01MapCompletBLK107[];
extern unsigned char Level01MapCompletBLK108[];
extern unsigned char Level01MapCompletBLK109[];
extern unsigned char Level01MapCompletBLK110[];
extern unsigned char Level01MapCompletBLK111[];
extern unsigned char Level01MapCompletBLK112[];
extern unsigned char Level01MapCompletBLK113[];
extern unsigned char Level01MapCompletBLK114[];
extern unsigned char Level01MapCompletBLK115[];
extern unsigned char Level01MapCompletBLK116[];
extern unsigned char Level01MapCompletBLK117[];
extern unsigned char Level01MapCompletBLK118[];
extern unsigned char Level01MapCompletBLK119[];
extern unsigned char Level01MapCompletBLK120[];
extern unsigned char Level01MapCompletBLK121[];
extern unsigned char Level01MapCompletBLK122[];
extern unsigned char Level01MapCompletBLK123[];
extern unsigned char Level01MapCompletBLK124[];
extern unsigned char Level01MapCompletBLK125[];
extern unsigned char Level01MapCompletBLK126[];
extern unsigned char Level01MapCompletBLK127[];
extern unsigned char Level01MapCompletBLK128[];
extern unsigned char Level01MapCompletBLK129[];
extern unsigned char Level01MapCompletBLK130[];
extern unsigned char Level01MapCompletBLK131[];
extern unsigned char Level01MapCompletBLK132[];
extern unsigned char Level01MapCompletBLK133[];
extern unsigned char Level01MapCompletBLK134[];
extern unsigned char Level01MapCompletBLK135[];
extern unsigned char Level01MapCompletBLK136[];
extern unsigned char Level01MapCompletBLK137[];
extern unsigned char Level01MapCompletBLK138[];
extern unsigned char Level01MapCompletBLK139[];
extern unsigned char Level01MapCompletBLK140[];
extern unsigned char Level01MapCompletBLK141[];
extern unsigned char Level01MapCompletBLK142[];
extern unsigned char Level01MapCompletBLK143[];
extern unsigned char Level01MapCompletBLK144[];
extern unsigned char Level01MapCompletBLK145[];
extern unsigned char Level01MapCompletBLK146[];
extern unsigned char Level01MapCompletBLK147[];
extern unsigned char Level01MapCompletBLK148[];
extern unsigned char Level01MapCompletBLK149[];

/* End of LEVEL01MAPCOMPLET.H */
