/*

 SCORESCREENMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Dylan\Documents\GameBoy\Renouveau\tuto_gameboy\VSCprojet_tutoGB_GamingMonsters\15 a game save - ma version\tuiles\keyboardTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define ScorescreenMapWidth 20
#define ScorescreenMapHeight 18
#define ScorescreenMapBank 0

extern unsigned char ScorescreenMap[];

/* End of SCORESCREENMAP.H */
