/*

 TERRAINMAP02.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : TerrainTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TerrainMap02Width 32
#define TerrainMap02Height 18
#define TerrainMap02Bank 0

extern unsigned char TerrainMap02[];

/* End of TERRAINMAP02.H */
