/*

 TERRAINMAP01.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : TerrainTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TerrainMap01Width 32
#define TerrainMap01Height 18
#define TerrainMap01Bank 0

extern unsigned char TerrainMap01[];

/* End of TERRAINMAP01.H */
