/*

 SHOOTERBGMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 32
   Tile set      : C:\Users\Dylan\Documents\GameBoy\Renouveau\tuto_gameboy\VSCprojet_tutoGB_GamingMonsters\Bilan Perso\5 beta ShootEmUp\tuiles\ShooterBgTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define ShooterBgMapWidth 20
#define ShooterBgMapHeight 32
#define ShooterBgMapBank 0

extern unsigned char ShooterBgMap[];

/* End of SHOOTERBGMAP.H */
