/*

 TERRAINMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : TerrainTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TerrainMapWidth 32
#define TerrainMapHeight 18
#define TerrainMapBank 0

extern unsigned char TerrainMap[];

/* End of TERRAINMAP.H */
