/*

 TERRAINMAPCOMPLET.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 150 x 18
   Tile set      : TerrainTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TerrainMapCompletWidth 150
#define TerrainMapCompletHeight 18
#define TerrainMapCompletBank 0

extern unsigned char TerrainMapComplet[];

/* End of TERRAINMAPCOMPLET.H */
